### ISSUE TITLE
Transaction doesn't show up even after rescan

### ISSUE THREAD

**Issue by BobleChinois** [chris-belcher/electrum-personal-server#115]
I run a BTCPay server and EPS 0.1.6, I recently noticed I received a transaction some time ago (early january), but failed to notice it before because it didn't show up on Electrum. 

In Electrum, I raised the gap limit all the way up to 200, and found the address that received the payment in Electrum. I raised the gap_limit in config.cfg to 200 too and did a rescan from the day before the one the transaction occurred. But after that the transaction still failed to show up in Electrum. I was clueless, and connected to an Electrum standard server to see if the transaction will show up, and it did.

What should I had done in EPS to make it spot this transaction?

**Comment by chris-belcher** [comment]
Thanks for the issue. Can you check that the bitcoin address associated with that transaction has really been imported into Core? Do this by running the command line `bitcoin-cli getaddressinfo <the-address>` (or running `getaddressinfo <the-address>` on the Debug Console) and checking whether `"iswatchonly": true`.

**Comment by BobleChinois** [comment]
Thanks for the answer, I did that and the result is `false`, what's strange is that I tried the first address of the list and it is false too, so I guess I did some mistake at some point:
* I checked the master pubkey in the config file ==> no mistake here
* I checked the 3 addresses that EPS gives me at startup against what's on Electrum ==> no mistake here

I imported others pubkey in the same file and they all work afaict.

Do you see anything else that I should check?

**Comment by chris-belcher** [comment]
So some address aren't imported for some reason. What is the value of `initial_import_count` in your config.cfg/ini file ?

Run `bitcoin-cli getaddressesbylabel electrum-watchonly-addresses` to get a list of all imported addresses. There might be clues if some are missing in a certain pattern.

**Comment by BobleChinois** [comment]
`initial_import_count` was `1000`

I did this `bitcoin-cli` command and wrote the output to a file, I compared it to the addresses in Electrum and I noticed that only the first 99 addresses were effectively imported in EPS. 

I'm doing a rescan and see if something worth of interest show up in bitcoind's log.

**Comment by chris-belcher** [comment]
Thanks, that's very useful information.

The way the code works now is that it only checks whether the first address of each master public key is imported. I'd say there should be an edit where the server checks that all addresses have been imported, and imports more if needed.

Perhaps your value used to be `100` and then was changed, but the server is coded not to check so that change didn't have an effect. Also possibly the server shut down after importing only 99.

**Comment by BobleChinois** [comment]
Ok I found the relevant piece of code, if I understood well it is necessary to delete bitcoind's `wallet.dat` in order to rescan for more addresses, is that correct?

This issue looks quite similar indeed.

I need some time to figure things out.

**Comment by chris-belcher** [comment]
> if I understood well it is necessary to delete bitcoind's `wallet.dat` in order to rescan for more addresses, is that correct?

Yes. To be completely precise, deleting it is required to _import_ more addresses.

**Comment by chris-belcher** [comment]
Do you run the source release? You could try editing this line https://github.com/chris-belcher/electrum-personal-server/blob/master/electrumpersonalserver/server/transactionmonitor.py#L33 to have a different label (for example "electrum-watchonly-addresses2" instead)

**Comment by BobleChinois** [comment]
Ok now that's interesting, I created another empty wallet and defined it as `wallet_file`, I did a rescan and now it only imported the first 12 addresses for this wallet! 

I imported 3 wallets with an `initial_import_count` of 1000 and a `gap_limit` of 200. I counted 4,012 imported addresses in this wallet.

**Comment by chris-belcher** [comment]
WTF

The current version of EPS is 0.1.7 rather than 0.1.6, so maybe updating it will help.

Please write what OS you're using and which version. I'll try to reproduce it as the bug of not importing addresses seems very serious.

**Comment by BobleChinois** [comment]
I didn't tell you... I already updated to 0.1.7.

I created a new wallet and imported addresses once again, when I do a `bitcoin-cli getaddressesbylabel electrum-watchonly-addresses` and `grep` the address that received funds I can see it, so it seems it worked this time. 

It reminds me that last time I imported addresses in Bitcoin Core I had to interrupt the process and start it again, could it be that it messed up with the import function, like it imported the first 12 addresses, then got interrupted, then started over, see the first address, assumes the wallet was already imported and skipped it?

**Comment by chris-belcher** [comment]
> It reminds me that last time I imported addresses in Bitcoin Core I had to interrupt the process and start it again, could it be that it messed up with the import function, like it imported the first 12 addresses, then got interrupted, then started over, see the first address, assumes the wallet was already imported and skipped it?

Yeah that would do it.

I should change the code to not just check the first address, but all the addresses (even if that would slow it down a bit)

**Comment by BobleChinois** [comment]
Ok so I guess the problem was from the beginning that I interrupted the import of addresses (first time was a while ago so I forgot but it's possible), and then trying to import more addresses obviously won't do any good since I wasn't aware that I needed to delete `wallet.dat` first. Case closed I think.

**Comment by chris-belcher** [comment]
One way to improve this situation is to have EPS check the length of the result of `getaddressesbylabel` to see whether at least the number of imported addresses is sane.

**Comment by BobleChinois** [comment]
Ok, I started working in another way, which is to test if the n address in an `initial_import_count` of n is in the `getaddressesbylabel` output when we test the 3 first addresses. I'm trying to test it I don't know if it would work. I'll open a PR it will be easier to discuss.

**Comment by BobleChinois** [comment]
Hi, I finally had the time to test it, and after I corrected a couple typo the last commit seems to work!
Here's what I've done:
* I created a testnet wallet on Electrum
* I created a new wallet in Bitcoin Core
* I modified the `config.ini` file with the masterpubkey and the Bitcoin Core's wallet
* On startup, I let electrumpersonalserver start the wallet import, and killed it after a while
* I checked that the first 3 addresses were actually imported in the BC wallet with `getaddressesbylabel`
* I ran EPS again, and it started again the wallet import
* I reset to the current master, build, install, and started electrumpersonalserver: it happily skipped the wallet import as expected

Tell me if you spot something else I should cover in this test. Maybe I should try it on mainnet?

**Comment by chris-belcher** [comment]
I think that's a fine test, thanks. There's no real need to try on mainnet because Bitcoin Core behaves the same on both networks.

**Comment by stevysg** [comment]
hi, i am running a full node on a raspberry pi (raspibolt) using the guide from stadicus (https://stadicus.github.io/RaspiBolt/).
I've set up a full node several times and eps was working (most of the times, sometimes i got connection problems, i use electrum with a ledger hardware wallet).
I set up a new one with bitcoin core 0.18.0 / lnd 0.6.1 / eps 0.1.7 because i had some problems with permissions ( i think, i used extFS for MacOs and somehow messed it up) and now my electrum wallet shows 0 transactions and 0 wallet balance. The first thing i did was to delete wallet.dat and reimport my keys, since that didnt help i set a new node up again and rescanned ofc. Then i increased initial_import_count to 6000 with a rescan but that didnt help either.

i am running my node in TOR only mode, can that be the root of the problem?

here are my logs:

INFO:2019-06-16 20:49:35,659: Starting Electrum Personal Server
INFO:2019-06-16 20:49:35,659: Logging to /tmp/electrumpersonalserver.log
INFO:2019-06-16 20:49:35,837: Displaying first 3 addresses of each master public key:
INFO:2019-06-16 20:49:36,057: 
any_name_works =>
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO:2019-06-16 20:51:58,414: Obtaining bitcoin addresses to monitor . . .
INFO:2019-06-16 20:52:03,095: Importing 1 wallets and 0 watch-only addresses into the Bitcoin node
INFO:2019-06-16 20:52:08,112: Importing 2000 addresses in total
[0%]... [5%]... [10%]... [15%]... [20%]... [25%]... [30%]... [35%]... [40%]... [45%]... [50%]... [55%]... [60%]... [65%]... [70%]... [75%]... [80%]... [85%]... [90%]... [95%]... [100%]
INFO:2019-06-16 20:53:14,043: Importing done
INFO:2019-06-16 20:53:14,045: Done.
If recovering a wallet which already has existing transactions, then
run the rescan script. If you're confident that the wallets are new
and empty then there's no need to rescan, just restart this script

:~/electrum-personal-server $ /home/bitcoin/.local/bin/electrum-personal-server --rescan /home/bitcoin/electrum-personal-server/config.ini
INFO:2019-06-16 20:54:03,844: Starting Electrum Personal Server
INFO:2019-06-16 20:54:03,844: Logging to /tmp/electrumpersonalserver.log
Enter earliest wallet creation date (DD/MM/YYYY) or block height to rescan from: XXXXXX
Rescan from block height XXXXXX ? (y/n):y
INFO:2019-06-16 20:54:32,533: Rescanning. . . for progress indicator see the bitcoin node's debug.log file
INFO:2019-06-16 22:34:31,205: end
~/electrum-personal-server $ /home/bitcoin/.local/bin/electrum-personal-server /home/bitcoin/electrum-personal-server/config.ini
INFO:2019-06-16 22:36:59,994: Starting Electrum Personal Server
INFO:2019-06-16 22:36:59,995: Logging to /tmp/electrumpersonalserver.log
INFO:2019-06-16 22:37:00,503: Displaying first 3 addresses of each master public key:
INFO:2019-06-16 22:37:00,739: 
any_name_works =>
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO:2019-06-16 22:37:00,740: Obtaining bitcoin addresses to monitor . . .
INFO:2019-06-16 22:39:23,623: Obtained list of addresses to monitor in 143.58850574493408sec
INFO:2019-06-16 22:39:23,625: Building history with 2000 addresses . . .
INFO:2019-06-16 22:39:24,557: Found 0 txes. History built in 0.13716340065002441sec
INFO:2019-06-16 22:39:24,558: Starting electrum server
INFO:2019-06-16 22:39:25,258: Listening for Electrum Wallet on ('0.0.0.0', 50002)
INFO:2019-06-16 22:41:40,061: Electrum connected from (‚XXX.XXX.XXX.XXX‘, 58933)
WARNING:2019-06-16 22:43:22,008: Mempool very large resulting in slow response by server. Consider setting `disable_mempool_fee_histogram = true`

So I disabled mempool fee histogram,  initial import count = 6000

INFO:2019-06-17 07:31:28,639: Starting Electrum Personal Server
INFO:2019-06-17 07:31:28,643: Logging to /tmp/electrumpersonalserver.log
INFO:2019-06-17 07:31:29,166: Displaying first 3 addresses of each master public key:
INFO:2019-06-17 07:31:29,400: 
any_name_works =>
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO:2019-06-17 07:31:29,401: Obtaining bitcoin addresses to monitor . . .
INFO:2019-06-17 07:50:32,276: Obtained list of addresses to monitor in 1143.5922684669495sec
INFO:2019-06-17 07:50:32,277: Building history with 16000 addresses . . .
INFO:2019-06-17 07:50:40,392: Found 0 txes. History built in 1.008793592453003sec
INFO:2019-06-17 07:50:40,396: Starting electrum server
INFO:2019-06-17 07:50:41,063: Listening for Electrum Wallet on ('0.0.0.0', 50002)
INFO:2019-06-17 07:53:33,639: Electrum connected from (‚XXX.XXX.XXX.XXX‘, 59217)

Thnx in advance for any help.

**Comment by BobleChinois** [comment]
Hi, have you tried what Chris advised me to do above, i.e. running `bitcoin-cli getaddressesbylabel electrum-watchonly-addresses` and check the result against the adresses in your Electrum wallet? I advise you to write the output in a file, it's easier to handle I think `bitcoin-cli getaddressesbylabel electrum-watchonly-addresses > adresses`
Besides except if you really need it for some reasons, I don't think it's useful to set the initial import count so high, I guess it will only slow you down especially on this kind of light hardware

**Comment by stevysg** [comment]
hi, thnx for ur answer.
i checked the adresses in my electrum wallet with the output from bitcoin-cli getaddressesbylabel electrum-watchonly-addresses > adresses and all the addresses i can see in electrum are there.

**Comment by stevysg** [comment]
when starting eps i get this msg:
Address not known to server, hash(address) = XXXXXXXXXXXXXXXXX.
This means Electrum is requesting information about addresses that are missing from Electrum Personal Server's configuration file.

**Comment by chris-belcher** [comment]
> edit:
> i fixed my problem, had nothing to do with eps. it was a problem with electrum wallet.

Can you tell us what the problem was and what you did to solve it?

**Comment by stevysg** [comment]
I tried connecting to other notes and the tx still didnt show up so when initialising my hardware wallet with electrum (ledger), i choose "p2sh-segwit" (p2wpkh-p2sh) as derivation path (m/84'/0'/0') although i thought i am using a native segwit wallet (?p2wpkh).
I tried this before but forget to change the master-public-key which is ofc different when using another derivation path.

**Comment by BobleChinois** [comment]
By the way I think we can close the issue now
