### ISSUE TITLE
Electrum stuck at sync when connected using SSH port forwarding over a VPN

### ISSUE THREAD

**Issue by sunknudsen** [chris-belcher/electrum-personal-server#136]
Running a full node on a server located on the same subnet as my Mac.

The server is connected to a remote VPN server to which my Mac is also connected (I can reliability SSH to the server from my Mac and latency is reasonable).

I am running EPS localhost on my Mac and using SSH port forwarding (`ssh user@*.*.*.* -L 8332:127.0.0.1:8332`) to forward port 8332 over the VPN to the server (this setup would allow me to connect to the server when remote while encrypting the data in transit).

This setup works fine when no new transactions have occurred but fails when there are (an unconfirmed transaction for instance). Electrum gets stuck at `Synchronizing... (29/31)`. A few minutes later it displays `Not connected`. And eventually, it connects again but fails and the cycle is repeated.

Last line from EPS logs is:

```
DEBUG:2019-07-06 08:**:**,***: => {"jsonrpc": "2.0", "method": "blockchain.block.headers", "id": 1**, "params": [5*****, 1***]}
```

Last lines from Electrum logs are:

```
I/n | network | network: retrying connections
I/i | interface.[localhost:50002] | disconnecting due to: OSError("Multiple exceptions: [Errno 61] Connect call failed ('::1', 50002), [Errno 60] Connect call failed ('127.0.0.1', 50002), [Errno 61] Connect call failed ('fe80::1%lo0', 50002, 0, 1)",)
I/n | network | couldn't launch iface localhost:50002:s -- CancelledError()
I/n | network | connecting to localhost:50002:s as new interface
```

Looks like somehow EPS fails to receive the large `hex` payload returned by `blockchain.block.headers`.

Someone has a hint to what could be causing this? Everything else works fine through the VPN.

Thanks!

**Comment by chris-belcher** [comment]
So right now you're running a full node on your VPN server but EPS is running on your local Mac machine(?)

I think the best thing for you to do is to run EPS also on your remote VPN server i.e. on the same machine as your full node. Then create an SSH tunnel with `ssh user@*.*.*.* -L 50002:127.0.0.1:50002` and have your Electrum connect to the EPS over that tunnel.

The way you're doing it is the JSON-RPC bitcoin interface is being tunnelled over SSH. In order to reply to the `blockchain.block.headers` method the EPS must make thousands of individual RPC calls to obtain the block headers. If each of those RPC requests went over an SSH tunnel then I can imagine it would be slow and unreliable.

**Comment by sunknudsen** [comment]
> So right now you're running a full node on your VPN server but EPS is running on your local Mac machine(?)

Not quite, the full node is running on a server that connects to a private VPN to which my Mac also connects (so basically both are on the same virtual distributed private subnet).

> I think the best thing for you to do is to run EPS also on your remote VPN server i.e. on the same machine as your full node.

I was trying to keep as much as possible on my Mac but I will try that.

> In order to reply to the blockchain.block.headers method the EPS must make thousands of individual RPC calls to obtain the block headers.

I was imagining some kind of bottleneck like this. Thanks for shedding light on it. Still strange that this wouldn't work over the VPN. Feels like a needle in a haystack kind of edge case.

Thanks for the follow up Chris!
