### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by rurouni22** [chris-belcher/electrum-personal-server#150]
Hello i am wondering if addresses are imported to the wallet permanently or to the memory for temporary? I have too many addresses to check on my electrum client and it takes a long time to import after every restart. Is there a config to make this faster?

**Comment by rurouni22** [comment]
I have learned that it imports them into wallet dat file but after first import it takes too much time to start the service. i think it might be because it is checking if all addresses are there. can i make it like it checkes first 10 and last 10? so it wont check 50k addresses everytime i start the wallet.

**Comment by chris-belcher** [comment]
EPS takes a long time because it generates all the addresses on startup. Issue #112 is relevant here. EPS needs all the addresses because it has to be ready in case Electrum requests them, so it's not possible to just generate the first and last 10. And finally, EPS already only checks the that the first and last few addresses have been imported.

**Comment by rurouni22** [comment]
What i mean is that it takes time after initial startup too. I checked wallet.dat before importing and it was like KBs and after initial startup it was around 30mb. Initial startup took around 2 hours. then i tried several times but it still takes 2 hours even though addresses are imported to wallet.dat. It's fine though i am running it on a Raspberry Pi and it is on all the time. Just wondered why it takes the same time after first startup.

**Comment by chris-belcher** [comment]
It takes that time because EPS uses the master public keys to generate addresses.
