### ISSUE TITLE
Error: The wallet already contains the private key for this address or script

### ISSUE THREAD

**Issue by themighty1** [chris-belcher/electrum-personal-server#18]
Hi, I was following the README with a pruned node.
I added one address to the watch-only config section.
When running ./server.py for the second time, Im getting this:

 [  LOG] Importing 0 wallets and 1 watch-only addresses into the Bitcoin node
 [  LOG] Importing 1 addresses in total
[0%]... [10%]... [20%]... [30%]... [40%]... [50%]... [60%]... [70%]... [80%]... [90%]... Traceback (most recent call last):
  File "./server.py", line 495, in <module>
    main()
  File "./server.py", line 473, in main
    log)
  File "/home/user/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 42, in import_addresses
    rpc.call("importaddress", [a, ADDRESSES_LABEL, False])
  File "/home/user/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'message': 'The wallet already contains the private key for this address or script', 'code': -4}

Is this a bug?

**Comment by fivepiece** [comment]
This error happens when trying to add a watchonly address, script or pubkey that the wallet already has the private key for.
If you want a watchonly wallet with these addresses (as this is what EPS needs), you might want to use the multiwallet setup and import the address(es) to a this new wallet that won't have the private keys for them.
You'll most likely need to rescan so the new wallet catches up to past transactions.

**Comment by themighty1** [comment]
Thanks

**Comment by andronoob** [comment]
@fivepiece Couldn't this error be ignored?
