### ISSUE TITLE
Electrum wallet doesn't connect, help troubleshooting

### ISSUE THREAD

**Issue by polaris1205** [chris-belcher/electrum-personal-server#197]
First of all, thanks for all the work!

I followed the tutorial for windows but Electrum is not connecting. My only clue is:

When I initiate the Electrum server, i get the expected "listening for electrum wallet". But the command window automatically closes as soon as I open the Electrum wallet application. Is that normal? I don't know any way to check if the server is up and running.

Any help is appreciated!

PS: I am running a pruned version of Bitcoin core. Does that affect the initial setup of the Electrum server?

**Below is the redacted log file** (running windows 7, all software are latest releases.)

> INFO:2020-06-05 01:12:29,287: Starting Electrum Personal Server 0.2.1
> INFO:2020-06-05 01:12:29,287: Logging to C:\Users\XXXX\AppData\Local\Temp/electrumpersonalserver.log
> DEBUG:2020-06-05 01:12:29,288: Process ID (PID) = 6324
> DEBUG:2020-06-05 01:12:29,288: obtaining auth from .cookie
> DEBUG:2020-06-05 01:12:29,310: Checking whether rescan is in progress
> INFO:2020-06-05 01:12:29,341: Displaying first 3 addresses of each master public key:
> INFO:2020-06-05 01:12:29,344: 
> Wallet 1 =>
> 	bc1...
> 	bc1...
> 	bc1...
> INFO:2020-06-05 01:12:29,349: 
> Wallet_2 =>
> 	bc1...
> 	bc1...
> 	bc1...
> INFO:2020-06-05 01:12:29,351: Obtaining bitcoin addresses to monitor . . .
> INFO:2020-06-05 01:12:32,144: Obtained list of addresses to monitor in 2.8331620693206787sec
> INFO:2020-06-05 01:12:32,144: Building history with 4000 addresses . . .
> DEBUG:2020-06-05 01:12:32,198: listtransactions skip=0 len(ret)=4
> DEBUG:2020-06-05 01:12:32,198: adding obtained tx=...
> DEBUG:2020-06-05 01:12:32,202: adding obtained tx=...
> DEBUG:2020-06-05 01:12:32,207: adding obtained tx=...
> DEBUG:2020-06-05 01:12:32,219: adding obtained tx=...
> DEBUG:2020-06-05 01:12:32,241: unconfirmed_txes = defaultdict(<class 'list'>, {})
> DEBUG:2020-06-05 01:12:32,241: reorganizable_txes = []
> DEBUG:2020-06-05 01:12:32,241: last_known_wallet_txid = ('...', '...')
> INFO:2020-06-05 01:12:32,241: Found 4 txes. History built in 0.09600520133972168sec
> DEBUG:2020-06-05 01:12:32,242: Starting electrum server
> DEBUG:2020-06-05 01:12:32,242: using cert: certs/cert.crt, key: certs/cert.key
> INFO:2020-06-05 01:12:32,242: Listening for Electrum Wallet on ('127.0.0.1', 50002)
> 
> If this project is valuable to you please consider donating:
> 	bc1qwt8kh83dpdj4yuquvsf28rhcft2rjh6jvy6678

**Comment by chris-belcher** [comment]
Thanks for the issue.

This is possibly this is the same error as https://old.reddit.com/r/Bitcoin/comments/gwpjyk/electrum_personal_server_021_features_massive/fsy8cas/

I think the problem might be caused by this commit: https://github.com/chris-belcher/electrum-personal-server/commit/dce6bff4768756c4ac2b0856d29ff9fe08348a15 Because it seems on windows sometimes OSError is raised and the new code doesn't catch that error but exits instead.

I'll fix this and create a minor release, but it will have to be in a couple of days because of my schedule.

Unitl then, could try downloading the older Electrum Personal Server version 0.2.0 instead, since that should work.

Pruning shouldn't affect this error, but it makes rescanning your Core wallet a bit harder. That's only a problem if your wallet already has transactions on it which are older than the pruning cutoff date. In your debug log it looks like EPS found 4 transactions, so that probably means rescanning already happened and succeeded. So no problem there.

**Comment by polaris1205** [comment]
Using 0.20 worked like a charm! Thanks Chris!
