### ISSUE TITLE
Can't make my electrum wallet work with remote electrum personal server

### ISSUE THREAD

**Issue by abellybeer** [chris-belcher/electrum-personal-server#206]
I install bitcoin core and electrum personal server on a VPS and currently I am still downloading the whole blockchain. So far 62gb downloaded.

My question is: how do I open putty and create a ssh tunnel between my laptop and my vps to allow my electrum wallet to connec to my full node?

I already opened ports on vps and my laptop and even change ips on config.ini to see if this would make it work but still the same.

What am I missing here?

**Comment by chris-belcher** [comment]
EPS needs to listen on localhost (also called 127.0.0.1), that's already the default value so you don't need to change anything in `config.ini`.

For an SSH tunnel you need to connect to your VPS via SSH and tell the SSH application to create a tunnel, that means that when your Electrum on your laptop connects to localhost it will actually be connecting to the SSH application, and that SSH will send all that data to your VPS and into the EPS application running there. To actually create such a tunnel with SSH, on the command line the command would be something like: `ssh your_vps_username@hostname_of_your_spv -L 50002:localhost:50002`. The number 50002 refers to the port number used by EPS by default.

You asked for help with putty not the command line SSH application. I just searched the web to get these instructions: https://blog.devolutions.net/2017/4/how-to-configure-an-ssh-tunnel-on-putty You need to tell putty to create an ssh tunnel on port 50002 connecting to localhost.

Also, all this will be much easier if you wait for your Bitcoin Core to finish synchronizing, because EPS doesn't fully start up until it detects that Core is sync'd.

**Comment by nicholascarballo** [comment]
I just had to wait for my bitcoin core to sync to be able to make my tunnel work. Now I am currently rescanning to return all my wallet transactions using --rescan option on electrum-personal-server.

It should take a while still. 

Thank you!
