### ISSUE TITLE
transaction is lost forever with tor broadcasting and tor not running

### ISSUE THREAD

**Issue by monkey-jsun** [chris-belcher/electrum-personal-server#220]
Quick steps to duplicate:

1. disable tor on the host where EPS and bitoind are running
2. configure EPS to use tor only, "broadcast_method = tor"
3. send money from electrum wallet, and the transaction is lost in no-man's land

It will be shown in "send' tab, but not in history.  Situation does not recover even if later tor is re-enabled.

**Comment by chris-belcher** [comment]
Thanks for the bug report

**Comment by chris-belcher** [comment]
I'm thinking deeply about this lately.

Transaction broadcast is never guaranteed, even the original bitcoin whitepaper talks about how transactions and blocks only need to be broadcast on a best-effort basis. Electrum's history tab only gets populated when it detects the transaction out there in the mempool or in blocks. So even Electrum itself realizes that broadcast can fail. If it fails the user should realize and try again somehow, maybe fixing tor or their internet.

I think the best way to deal with this issue is to make EPS detect that it was unable to connect to Tor and display some kind of error message.

**Comment by chris-belcher** [comment]
I coded up a feature where the broadcasting threads send a notify message to the server thread, which waits for that message before sending a reply back to the client.

* If EPS cant connect to Tor, then EPS will almost immediately send back an error message to the client.
* The first time EPS manages to upload its transaction to a peer, it will send back a success message to the client.
* Until then, the client will display as "Please wait. Broadcasting transaction..." dialog.
* After 20 seconds the notification wait in EPS will time out, and it will send back a _success_ message to the client. The reasoning being that after 20 seconds any network errors like Tor not running would have already been detected, and a delay of 20 seconds is most likely due to Tor and the bitcoin network just being slow.
