### ISSUE TITLE
why must EPS have master public or watch address to work?

### ISSUE THREAD

**Issue by monkey-jsun** [chris-belcher/electrum-personal-server#221]
I successfully followed the instructions and was able to connect an eletrum wallet to a full node through EPS.  In my setup, EPS and full node runs on an internet-connected machine, while electrum wallet runs on another machine which can only talk to full node through private network (occasionally).

I did not like the fact the full node is watching all my transactions, because full node is exposed in internet and could potentially be hacked, in which case hacker would be able to see all my transactions (BTW, I configure EPS to use Tor only for broadcast new instructions for additional privacy).

So I tried to not set any master public key, and EPS complained.  Then I tried to set an irrelevant master public key.  EPS did not compalin, but I could send any money, because EPS would reject eletrum wallet requests.

Why must EPS know about the wallet info on electrum wallet?  Can we configure so that EPS and full node are agnostic about the electrum wallet details, only provide blockchain info to electrum and let electrum to track transactions/balances, etc?  I feel this way would provide maximum privacy and security.

**Comment by jmacxx** [comment]
EPS is a very thin client, essentially translating message formats between Electrum and the full node.  Bitcoin Core is doing all the heavy lifting, so it must have the details in a wallet.  

The alternative is to make the entire blockchain visible to Electrum, which is the purpose of [ElectrumX](https://electrumx-spesmilo.readthedocs.io/en/latest/).

**Comment by monkey-jsun** [comment]
Thanks for quick response, James.  Before this discovery, I had thought Electrum would work like following:

- For sync'ing, just loop through all pub keys or addresses and ask full node for related transactions (since last sync up time to reduce traffic).  From there, it can figure out transaction history and balances.
- For sending, Electrum would construct a valid send message signed its private key and ask EPS to broadcast to bitcoin network (in fact, with Tor option EPS does not even send to the associated full node)

As you can see, in this picture full node and EPS don't need to remember anything about the wallet.  What is wrong with my understanding?  What is preventing Electrum from doing what I was thinking?  At least for the sending part?

Would really appreciate your insight and knowledge on this.

**Comment by jmacxx** [comment]
Bitcoin core is not optimized to provide related transactions for addresses unless they are in a wallet.  Notice how long it takes to import an xpub into bitcoin core/EPS?  It can take hours to sync the wallet because it is scanning the blockchain and building the relevant indexes.  (That's also why it asks for a start date to reduce the amount of blockchain it has to search.)  Building and maintaining the relevant indexes to make the blockchain searchable like ElectrumX does takes ~80Gb extra storage.  So that's why it is not a feature of Bitcoin core.

As for why you cannot broadcast a transaction; I don't know.  IMHO there's no point using EPS misconfigured with an irrelevant master public key.

**Comment by monkey-jsun** [comment]
Thanks for your explanation.  It makes a lot of sense to me now.

One last question - if I follow you correctly, ElectrumX would not need to know your wallet details  (i.e., master pub key or watch addresses) because it has its own transaction database.  Is this understanding correct?

**Comment by chris-belcher** [comment]
ElectrumX or any electrum server would also know all the addresses in your electrum bitcoin wallet, it must know your addresses so that it can reply back to the electrum wallet with the wallet's history and balance. The only difference with EPS is that you need to set it up with your master public key *beforehand*, but that's a only small detail in terms of privacy.

Regarding concerns about an online full node being hacked and therefore the hacker learning your privacy-relevant information: using bitcoin inherently requires a connection to the internet, so there's no real way around this. The best defence is to keep your machine secure (for example, by always installing all the security updates to your OS, keeping it behind a firewall, not using the machine for any other activity such as web browser or email).

One possible alternative for extreme privacy and offlineness is to access bitcoin network data via blockstream satellite: https://medium.com/hackernoon/completely-offline-bitcoin-transactions-4e58324637bd Then your full node doesn't connect to the internet, and it becomes much harder to tell whether you're even using bitcoin. The tradeoff is that you now have a single point of failure of Blockstream's network of satellites, and in theory they could shut down one day.

**Comment by monkey-jsun** [comment]
Thanks, Chris.  I understand your explanation.  Please allow me ask slightly differently.  With ElectrumX,  one can  run full node with wallet feature disabled - is this understanding true?

I'm not looking for the "extreme privacy" you were implying.  I just thought, if I were to run a full node, it would be nice it could also help bitcoin community in addition to myself.  But in the end even requiring wallet info and feature is a small cost in terms of privacy code.  It was just a surprise to me.  :)

Thanks for all the great work!

**Comment by chris-belcher** [comment]
> With ElectrumX, one can run full node with wallet feature disabled - is this understanding true?

Correct

Regarding helping the bitcoin community: by using a wallet backed by a full node you're already doing a pretty huge help for bitcoin, because your wallet now actually checks the rules of bitcoin when doing economic activity. So for example if someone printed more than 21 million bitcoins and tried to pay you with them, your wallet would reject the transaction and therefore the fraudster wouldn't be able to get away with it. That's crucial to bitcoin's security, way more than stuff like having port 8333 open.
