### ISSUE TITLE
Network issue: server_sock.bind(hostport), Windows10

### ISSUE THREAD

**Issue by HelgeHunding** [chris-belcher/electrum-personal-server#91]
I'm trying to write a tutorial for how to run this great project on Windows10, but am getting stuck myself :smile: 

I think it's a network issue related to Windows. 
The installation and everything works fine, I was able to run the server to import (and rescan) for a few addresses (so there is a connection between Bitcoin Core and the server). But when doing the final run I'm getting this error
```
INFO:2019-02-28 13:58:42,860: Starting electrum server
Traceback (most recent call last):
  File "c:\users\user1\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user1\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\Scripts\electrum-personal-server.exe\__main__.py", line 9, in <module>
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\electrumpersonalserver\server\common.py", line 704, in main
    poll_interval_connected, certfile, keyfile)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\electrumpersonalserver\server\common.py", line 409, in run_electrum_server
    server_sock = create_server_socket(hostport)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\electrumpersonalserver\server\common.py", line 400, in create_server_socket
    server_sock.bind(hostport)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```
A lot of searching and testing and I haven't been much wiser. What was suggested and what I've tried without luck:
Restart the computer, turn off firewall and antivirus, run as administrator, reset TCP connections and use 
TCPView to monitor all connections to make sure that no other program uses the port the server is trying to use.
But nothing has worked so far. I do not know much about networks, but all I can see on related ports is that bitcoin-qt.exe is listening to port 8332 which I guess is expected?

The server is spinning up a lot of System processes that tries to connect to port 8332 but it fails.

I played around a bit with the code to try something else. If I changed line 400 in common.py to a hard-coded address 
`server_sock.bind(("0.0.0.0", 8332))`
I got through to the message 
`Listening for Electrum Wallet on ('127.0.0.1', 50002)`
But Electrum doesn't detect anything. I can see Electrum trying to make connections to remote port 50002 on localhost, but it fails because nothing is listening to that port. So I guess that only broke something. This only "worked" with `0.0.0.0` and not with `127.0.0.1`. Changing to `0.0.0.0` in the config-file didn't work.

Everything is on one machine. But to be sure, I've opened ports and disabled my VPN. Anyone with an idea?

**Comment by chris-belcher** [comment]
Thanks for the issue, here are some thoughts.

1. The correct way to change the host and port is by editing `config.cfg`. You said editing didn't work, which is definitely a bug and should be fixed. I'll try running EPS on windows which I haven't done yet, and fixing it when I get time, or you could try adding print statements in places and seeing why it doesn't work. Other users have reported that changing to `0.0.0.0.` works correctly for them, but I think they were all using non-windows.

1. Don't use port 8332 because Bitcoin Core RPC uses that, perhaps try port 8000 (which is just a number I invented now)

1. When you change the bound port number, you also need to tell Electrum to connect to that port instead of 50002. So either by running command line `--server localhost:8000:s` or in the Electrum GUI going Tools -> Network -> Server and changing the port number to 8000.

1. I intend to eventually package up the project with pyinstaller so that it will be a single windows .exe file (see https://github.com/chris-belcher/electrum-personal-server/issues/63#issuecomment-435919552) After that installing on windows should be much easier, but I fear your tutorial may become out of date (Thought it looks like didn't have any trouble installing)

**Comment by HelgeHunding** [comment]
Thanks a lot for the help. Changing the port in the config-file did the trick (and it's able to run with localhost)!
```
[electrum-server]
# 0.0.0.0 to accept connections from any IP
#127.0.0.1 to accept from only localhost
host = 127.0.0.1 
port = 8000
```
I tried to change it from 50002 to like 50000 before without success. So, your invented number was great! Might be because Windows use a lot of local ports with numbers randomly between 49000 and 65000 and that must've caused the issue even though I couldn't see that any process used them.

A single .exe file would be great and I'd happily update the tutorial when that is done (just want to see people running those full nodes). Feel free to hit me up if you need anything tested on Windows. Cheers

**Comment by chris-belcher** [comment]
>  Feel free to hit me up if you need anything tested on Windows.

If this offer is still open, please have a look at issue #106
